# Generated by Django 5.1.6 on 2025-04-04 03:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_user_delete_userlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmpassword',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
