# Generated by Django 5.1.6 on 2025-04-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_user_confirmpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmpassword',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
